version: "2"

services:
  db:
    container_name: pvnauction_db
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql_passwd:/run/secrets/mysql_passwd
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: auction
      MYSQL_USER: auction
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_passwd
    restart: always
  nodejs:
    container_name: pvnauction_nodejs
    image: node:8
    user: "node"
    working_dir: /home/node/app
    environment:
      - VIRTUAL_HOST=socket.auction.punch.local
      - VIRTUAL_PORT=3000
      - NETWORK_ACCESS=internal
    volumes:
      - ./:/home/node/app
    command: ["/bin/bash", -c, "npm install && npm start"]
    depends_on:
      - db
    restart: always
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
