version: "2"

services:
  db:
    container_name: pvnauction_db
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/mysql_passwd:/run/secrets/mysql_passwd
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=auction
      - MYSQL_USER=auction
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_passwd
    restart: always
  nodejs:
    container_name: pvnauction_nodejs
    image: node:8
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: ["./docker/run.sh"]
    depends_on:
      - db
    restart: always
