version: "2"

services:
  db:
    container_name: pvnauction_db
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/mysql_passwd:/run/secrets/mysql_passwd
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=auction
      - MYSQL_USER=auction
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_passwd
    ports:
      - "9306:3306"
    restart: always
    networks:
      - localnet
  nodejs:
    container_name: pvnauction_nodejs
    image: node:8
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: ["./docker/run.sh"]
    environment:
      - VIRTUAL_HOST=server.auction.punch.vn
      - VIRTUAL_PORT=3000
    expose:
      - "3000"
    depends_on:
      - db
    restart: always
    networks:
      - localnet
      - reverse-proxy

networks:
  localnet:
    driver: bridge
  reverse-proxy:
    external:
      name: reverse-proxy
